version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "[01] to-upper"
      - "[02] to-do"
      - "[03] high-level-framework"
      - "[04] asset-handling"
      - "[05] interacting-with-the-base-layer"
      - "[06] delegate-call-voucher"
      - "[07] auction"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "docker" 