// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Mugen-Builders/to-do-sqlite/internal/domain"
	"github.com/Mugen-Builders/to-do-sqlite/internal/infra/cartesi/advance_handler"
	"github.com/Mugen-Builders/to-do-sqlite/internal/infra/cartesi/inspect_handler"
	"github.com/Mugen-Builders/to-do-sqlite/internal/infra/repository"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewAdvanceHandlers(gormDB *gorm.DB) (*AdvanceHandlers, error) {
	todoRepositorySQLite := repository.NewTodoRepositorySQLite(gormDB)
	todoAdvanceHandlers := advance_handler.NewTodoAdvanceHandlers(todoRepositorySQLite)
	advanceHandlers := &AdvanceHandlers{
		TodoAdvanceHandlers: todoAdvanceHandlers,
	}
	return advanceHandlers, nil
}

func NewInspectHandlers(gormDB *gorm.DB) (*InspectHandlers, error) {
	todoRepositorySQLite := repository.NewTodoRepositorySQLite(gormDB)
	todoInspectHandlers := inspect_handler.NewTodoInspectHandlers(todoRepositorySQLite)
	inspectHandlers := &InspectHandlers{
		TodoInspectHandlers: todoInspectHandlers,
	}
	return inspectHandlers, nil
}

// wire.go:

var setTodoRepositoryDependency = wire.NewSet(repository.NewTodoRepositorySQLite, wire.Bind(new(domain.TodoRepository), new(*repository.TodoRepositorySQLite)))

var setAdvanceHandlers = wire.NewSet(advance_handler.NewTodoAdvanceHandlers)

var setInspectHandlers = wire.NewSet(inspect_handler.NewTodoInspectHandlers)

type AdvanceHandlers struct {
	TodoAdvanceHandlers *advance_handler.TodoAdvanceHandlers
}

type InspectHandlers struct {
	TodoInspectHandlers *inspect_handler.TodoInspectHandlers
}
