// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Mugen-Builders/to-do-memory/configs"
	"github.com/Mugen-Builders/to-do-memory/internal/domain"
	"github.com/Mugen-Builders/to-do-memory/internal/infra/cartesi/advance_handler"
	"github.com/Mugen-Builders/to-do-memory/internal/infra/cartesi/inspect_handler"
	"github.com/Mugen-Builders/to-do-memory/internal/infra/repository"
	"github.com/google/wire"
)

// Injectors from wire.go:

func NewAdvanceHandlers(db *configs.InMemoryDB) (*AdvanceHandlers, error) {
	todoRepositoryInMemory := repository.NewTodoRepositoryInMemory()
	todoAdvanceHandlers := advance_handler.NewTodoAdvanceHandlers(todoRepositoryInMemory)
	advanceHandlers := &AdvanceHandlers{
		TodoAdvanceHandlers: todoAdvanceHandlers,
	}
	return advanceHandlers, nil
}

func NewInspectHandlers(db *configs.InMemoryDB) (*InspectHandlers, error) {
	todoRepositoryInMemory := repository.NewTodoRepositoryInMemory()
	todoInspectHandlers := inspect_handler.NewTodoInspectHandlers(todoRepositoryInMemory)
	inspectHandlers := &InspectHandlers{
		TodoInspectHandlers: todoInspectHandlers,
	}
	return inspectHandlers, nil
}

// wire.go:

var setTodoRepositoryDependency = wire.NewSet(repository.NewTodoRepositoryInMemory, wire.Bind(new(domain.TodoRepository), new(*repository.TodoRepositoryInMemory)))

var setAdvanceHandlers = wire.NewSet(advance_handler.NewTodoAdvanceHandlers)

var setInspectHandlers = wire.NewSet(inspect_handler.NewTodoInspectHandlers)

type AdvanceHandlers struct {
	TodoAdvanceHandlers *advance_handler.TodoAdvanceHandlers
}

type InspectHandlers struct {
	TodoInspectHandlers *inspect_handler.TodoInspectHandlers
}
