name: Build
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [
          "src/01",
          "src/02", 
          "src/03",
          "src/04",
          "src/05",
          "src/06",
          "src/tribes"
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: current

      - name: Install Cartesi CLI
        run: npm install -g @cartesi/cli@2.0.0-alpha.15

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Check system requirements
        run: cartesi doctor

      - name: Build ${{ matrix.project }}
        run: make build
        working-directory: ${{ matrix.project }}
      
      - name: Test ${{ matrix.project }}
        if: ${{ matrix.project != 'src/01' }}
        run: make test
        working-directory: ${{ matrix.project }}