name: build-and-test

on:
  push:
    tags:
      - "*"
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test Matrix
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - src/01
          - src/02
          - src/03
          - src/04
          - src/05
          - src/06
          - src/tribes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Setup Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: current
          cache: npm

      - name: Install Cartesi CLI
        run: npm install -g @cartesi/cli@2.0.0-alpha.15

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Verify Cartesi CLI system requirements
        run: cartesi doctor

      - name: Format Code
        run: make fmt
        working-directory: ${{ matrix.project }}

      - name: Build Project
        run: make build
        working-directory: ${{ matrix.project }}

      - name: Run Tests
        if: ${{ matrix.project != 'src/01' }}
        run: make test
        working-directory: ${{ matrix.project }}